spring:
  application:
    name:gateway
server:
  port:8083
eureka:
  client:
    service-cli:
      defaultZone: http://localhost:2222/eureka
zuul:
  routes:
    SERVER:
      path: /server/**
      service-id: SERVER

